import { ArrowRight, Banknote, CheckCircle2, PlayCircle, ShieldCheck, Sparkles } from "lucide-react";
import { InlineError, MetricTile, StatusPill, WorkspacePanel } from "../components/WorkspaceUI";
import { useAuditra } from "../hooks/useAuditra";
import { compact, executionLabel, money, pct, titleCase } from "../lib/format";
import { attentionCases, auditHealthLabel, auditHealthRatio, potentialExposure } from "../lib/product";

const stages = ["Create", "Close", "Verify", "Challenge", "Assure"];

export function HomePage() {
  const { world, audit, assurance, runtimeAI, runFiveMinuteDemo, setActivePage, isBusy, busyLabel, statusMessage, error } = useAuditra();
  const attention = attentionCases(audit);
  const exposure = potentialExposure(attention);
  const mode = runtimeAI?.investigation.execution_mode ?? "AI_UNAVAILABLE";
  return <div className="space-y-7">
    <section className="animate-fade-up overflow-hidden rounded-lg border border-white/10 bg-[radial-gradient(circle_at_top_left,rgba(34,211,238,0.16),transparent_34%),linear-gradient(135deg,rgba(15,23,42,0.96),rgba(7,10,16,0.98))] p-6 sm:p-8 lg:p-10">
      <div className="max-w-4xl"><StatusPill accent={mode === "REAL_GROQ_AI" ? "cyan" : "amber"} dot>{executionLabel(mode)}</StatusPill><h1 className="mt-5 text-4xl font-semibold leading-tight text-white sm:text-6xl">AUDITRA</h1><p className="mt-4 max-w-2xl text-xl leading-8 text-slate-300">From financial intent to verified control.</p><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-400">Create a controlled payment world, audit it, investigate exceptions with bounded AI, verify the result, then challenge the controller before deployment.</p></div>
      <div className="mt-7 flex flex-wrap gap-3"><button type="button" className="inline-flex min-h-12 items-center gap-2 rounded-md bg-gradient-to-r from-indigo-500 via-sky-500 to-cyan-400 px-6 text-sm font-semibold text-white shadow-[0_18px_44px_rgba(14,165,233,0.25)] transition hover:brightness-110" onClick={() => setActivePage("worlds")}><Sparkles className="h-4 w-4" />Create financial world</button><button type="button" className="inline-flex min-h-12 items-center gap-2 rounded-md border border-white/10 bg-white/[0.06] px-5 text-sm font-semibold text-white hover:bg-white/[0.1] disabled:opacity-50" disabled={isBusy} onClick={() => void runFiveMinuteDemo()}>{isBusy ? busyLabel || "Running" : <PlayCircle className="h-4 w-4" />}{isBusy ? statusMessage : "Run demo"}</button></div>
      <div className="mt-8 grid max-w-4xl grid-cols-5 gap-1 rounded-lg border border-white/10 bg-black/20 p-2">{stages.map((stage, index) => <div key={stage} className="text-center"><span className="mx-auto grid h-8 w-8 place-items-center rounded-md bg-cyan-400/10 text-xs font-semibold text-cyan-200">{index + 1}</span><span className="mt-2 block text-[11px] text-slate-500">{stage}</span></div>)}</div>
    </section>
    {error ? <InlineError error={error} /> : null}
    {world || audit ? <section className="animate-fade-up-delayed"><div className="mb-4 flex items-end justify-between gap-4"><div><div className="text-xs font-semibold text-cyan-300">Current workspace</div><h2 className="mt-1 text-xl font-semibold text-white">{world?.summary.merchant ?? "Audit workspace"}</h2></div>{audit ? <StatusPill accent={attention.length ? "amber" : "emerald"}>{auditHealthLabel(audit)}</StatusPill> : null}</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricTile label="Audit health" value={audit ? pct(auditHealthRatio(audit)) : "Ready"} detail={audit ? "Verified against hidden truth" : "Build an audit next"} icon={<ShieldCheck className="h-4 w-4" />} accent={attention.length ? "amber" : "emerald"} /><MetricTile label="Needs attention" value={audit ? compact(attention.length) : "-"} detail="Priority review queue" icon={<CheckCircle2 className="h-4 w-4" />} accent={attention.length ? "amber" : "emerald"} /><MetricTile label="Exposure" value={audit ? money(exposure) : money(world?.summary.payment_volume)} detail={audit ? "Potential open exposure" : "World payment volume"} icon={<Banknote className="h-4 w-4" />} accent={exposure ? "rose" : "cyan"} /><MetricTile label="Assurance" value={assurance ? titleCase(assurance.recommendation) : "Pending"} detail={assurance ? "Grade " + assurance.grade : "Runs after audit"} accent="indigo" /></div><div className="mt-5 flex flex-wrap gap-3"><button type="button" className="inline-flex min-h-11 items-center gap-2 rounded-md bg-white px-5 text-sm font-semibold text-slate-950" onClick={() => setActivePage(world && !audit ? "audits" : "review")}>{world && !audit ? "Audit world" : "Review findings"}<ArrowRight className="h-4 w-4" /></button><button type="button" className="inline-flex min-h-11 items-center gap-2 rounded-md border border-white/10 px-4 text-sm font-semibold text-slate-300 hover:bg-white/[0.06]" onClick={() => setActivePage("insights")}>Open insights</button></div></section> : <WorkspacePanel className="animate-fade-up-delayed"><div className="py-10 text-center"><h2 className="text-2xl font-semibold text-white">No financial worlds yet</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">Describe a financial world and Auditra will build one with hidden anomalies, evidence, and validation.</p><button type="button" className="mt-6 rounded-md bg-white px-5 py-3 text-sm font-semibold text-slate-950" onClick={() => setActivePage("worlds")}>Create world</button></div></WorkspacePanel>}
  </div>;
}
