import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BarChart3, FlaskConical, Gauge, TrendingUp } from "lucide-react";
import { InlineError, MetricTile, SectionTitle, SegmentedTabs, StatusPill, WorkspacePanel } from "../components/WorkspaceUI";
import { useAuditra } from "../hooks/useAuditra";
import { compact, money, pct, titleCase } from "../lib/format";
import { attentionCases, potentialExposure } from "../lib/product";
import { useState } from "react";
import type { AnomalyMode } from "../types/auditra";

type Tab = "patterns" | "evaluation" | "challenge";

export function InsightsPage() {
  const { audit, comparison, assurance, redTeam, runComparison, runRedTeam, breakController, isBusy, error, setActivePage } = useAuditra();
  const [tab, setTab] = useState<Tab>("patterns");
  if (!audit) return <Empty onClick={() => setActivePage("audits")} />;
  const attention = attentionCases(audit);
  const exposure = potentialExposure(attention);
  const exposureData = Object.entries(attention.reduce<Record<string, number>>((acc, item) => { acc[item.status] = (acc[item.status] ?? 0) + Number(item.decision.financial_impact ?? 0); return acc; }, {})).map(([status, value]) => ({ name: titleCase(status), value: Number(value.toFixed(2)) }));
  const failureData = Object.entries(audit.evaluation.metrics.failure_taxonomy).map(([name, count]) => ({ name: titleCase(name), value: count }));
  const rows = comparison?.comparison ?? audit.comparison.comparison;

  return <div className="space-y-7">
    <header className="animate-fade-up border-b border-white/10 pb-6"><StatusPill accent="indigo" dot>Insights</StatusPill><h1 className="mt-4 text-3xl font-semibold text-white sm:text-4xl">What the audit is telling you</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400 sm:text-base">Only the useful patterns: exposure, controller quality, and targeted challenge results.</p></header>
    {error ? <InlineError error={error} /> : null}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricTile label="Audit health" value={pct(audit.evaluation.metrics.accuracy)} detail="Hidden-truth evaluation" accent="emerald" icon={<Gauge className="h-4 w-4" />} /><MetricTile label="Needs attention" value={compact(attention.length)} detail={money(exposure) + " exposure"} accent={attention.length ? "amber" : "emerald"} /><MetricTile label="Financial error" value={money(audit.evaluation.metrics.financial_impact_of_errors)} detail="Measured after truth reveal" accent="rose" /><MetricTile label="Assurance" value={assurance ? titleCase(assurance.recommendation) : "Pending"} detail={assurance ? "Grade " + assurance.grade : "Run audit to score"} accent="cyan" /></div>
    <SegmentedTabs tabs={[{ id: "patterns", label: "Patterns" }, { id: "evaluation", label: "Evaluation" }, { id: "challenge", label: "Challenge" }]} active={tab} onChange={setTab} />
    {tab === "patterns" ? <div className="grid gap-5 xl:grid-cols-2"><Chart title="Exposure by issue" data={exposureData} currency /><Chart title="Failure taxonomy" data={failureData} /></div> : null}
    {tab === "evaluation" ? <WorkspacePanel><SectionTitle icon={<BarChart3 className="h-5 w-5" />} title="Controller evaluation" detail="Compare deterministic-only and AI-assisted runs on the same world." action={<button type="button" className="rounded-md bg-white px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50" disabled={isBusy} onClick={() => void runComparison()}>Run comparison</button>} /><div className="mt-5 grid gap-4 lg:grid-cols-2">{rows.map((row) => <div key={row.mode} className="rounded-lg border border-white/10 bg-white/[0.04] p-5"><div className="flex items-center justify-between"><h3 className="font-semibold text-white">{row.mode === "ai_assisted" ? "AI-assisted" : "Deterministic"}</h3><StatusPill accent={row.execution.execution_mode.startsWith("REAL_") ? "cyan" : row.mode === "ai_assisted" ? "amber" : "slate"}>{row.execution.execution_mode}</StatusPill></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Small label="Accuracy" value={pct(row.metrics.accuracy)} /><Small label="Precision" value={pct(row.metrics.precision)} /><Small label="Recall" value={pct(row.metrics.recall)} /><Small label="F1" value={pct(row.metrics.f1)} /></div></div>)}</div></WorkspacePanel> : null}
    {tab === "challenge" ? <WorkspacePanel><SectionTitle icon={<FlaskConical className="h-5 w-5" />} title="Challenge the controller" detail="Use the measured failure fingerprint to retest the controller against harder cases." />{assurance ? <div className="mt-5 rounded-lg border border-rose-400/20 bg-rose-400/10 p-4"><div className="text-sm font-semibold text-white">{titleCase(assurance.failure_fingerprint.pattern)}</div><p className="mt-2 text-sm leading-6 text-slate-400">{assurance.failure_fingerprint.root_cause}</p><div className="mt-4 flex flex-wrap gap-3"><button type="button" className="rounded-md bg-rose-500 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" disabled={isBusy} onClick={() => void runRedTeam(200)}>Run challenge</button>{(["STRESSED", "ADVERSARIAL", "CHAOS"] as AnomalyMode[]).map((mode) => <button key={mode} type="button" className="rounded-md border border-white/10 px-4 py-2 text-sm font-semibold text-slate-300 hover:bg-white/[0.06] disabled:opacity-50" disabled={isBusy} onClick={() => void breakController(mode, 500)}><TrendingUp className="mr-2 inline h-4 w-4" />{titleCase(mode)}</button>)}</div></div> : <div className="mt-5 text-sm text-slate-500">Assurance is still pending.</div>}{redTeam ? <div className="mt-5 rounded-lg border border-cyan-400/20 bg-cyan-400/10 p-4 text-sm text-cyan-100">Targeted retest: {titleCase(redTeam.comparison.verdict)}. Score {redTeam.comparison.retest_score.toFixed(1)}.</div> : null}</WorkspacePanel> : null}
  </div>;
}

function Chart({ title, data, currency = false }: { title: string; data: Array<{ name: string; value: number }>; currency?: boolean }) { return <WorkspacePanel><SectionTitle title={title} />{data.length ? <div className="mt-4 h-[320px]"><ResponsiveContainer><BarChart data={data}><CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.18)" vertical={false} /><XAxis dataKey="name" tick={{ fill: "#94a3b8", fontSize: 12 }} tickLine={false} axisLine={false} /><YAxis tick={{ fill: "#94a3b8", fontSize: 12 }} tickLine={false} axisLine={false} /><Tooltip formatter={(value) => currency ? money(Number(value)) : compact(Number(value))} contentStyle={{ background: "#0f172a", border: "1px solid rgba(255,255,255,0.1)", color: "#fff" }} /><Bar dataKey="value" fill="#22d3ee" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div> : <div className="mt-4 rounded-lg border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">No data for this chart.</div>}</WorkspacePanel>; }
function Small({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-white/10 bg-black/20 p-4"><div className="text-xs text-slate-500">{label}</div><div className="mt-2 text-lg font-semibold text-white">{value}</div></div>; }
function Empty({ onClick }: { onClick: () => void }) { return <WorkspacePanel><div className="py-16 text-center"><h1 className="text-2xl font-semibold text-white">No insights yet</h1><p className="mt-2 text-sm text-slate-500">Run an audit first so Auditra can reveal patterns.</p><button type="button" className="mt-6 rounded-md bg-white px-5 py-3 text-sm font-semibold text-slate-950" onClick={onClick}>Open audits</button></div></WorkspacePanel>; }
