import { ArrowRight, CheckCircle2, CircleAlert, FlaskConical, ShieldCheck } from "lucide-react";
import { InlineError, StatusPill } from "../components/WorkspaceUI";
import { useAuditra } from "../hooks/useAuditra";
import { compact, money, pct, titleCase } from "../lib/format";
import { attentionCases, potentialExposure } from "../lib/product";

export function InsightsPage() {
  const { audit, assurance, redTeam, runComparison, runRedTeam, comparison, isBusy, error, setActivePage } = useAuditra();
  if (!audit) return <Empty onClick={() => setActivePage("audits")} />;
  const metrics = audit.evaluation.metrics;
  const exceptions = attentionCases(audit);
  const retest = redTeam?.comparison;
  const fingerprint = assurance?.failure_fingerprint;

  return <div className="space-y-7 pb-8">
    <header className="control-header rise-in"><div className="product-name">AUDITRA</div><h1 className="control-title">Assurance</h1><p className="control-copy">A control report for the question that matters after a close: should this controller be trusted with the next batch?</p></header>
    {error ? <InlineError error={error} /> : null}
    <section><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="section-kicker">Hidden-ground-truth evaluation</div><h2 className="mt-1 text-xl font-semibold text-white">Independent control outcome</h2></div><StatusPill accent={assurance ? recommendationAccent(assurance.recommendation) : "amber"}>{assurance ? assurance.recommendation.replace(/_/g, " ") : "Scoring"}</StatusPill></div><div className="kpi-strip mt-4"><Kpi label="Accuracy" value={pct(metrics.accuracy, 2)} detail="truth revealed after run" tone="positive" /><Kpi label="Macro F1" value={pct(metrics.f1, 2)} detail="decision quality" tone="positive" /><Kpi label="Missed exception rate" value={pct(metrics.exception_false_negative_rate, 2)} detail="requires attention" tone={metrics.exception_false_negative_rate ? "danger" : "positive"} /><Kpi label="Financial error" value={money(metrics.financial_impact_of_errors)} detail="measured impact" tone={Number(metrics.financial_impact_of_errors) ? "danger" : "positive"} /><Kpi label="Cases reviewed" value={compact(exceptions.length)} detail="operational queue" tone={exceptions.length ? "warning" : "positive"} /><Kpi label="Control score" value={assurance ? assurance.score.toFixed(1) : "…"} detail={assurance ? `grade ${assurance.grade}` : "in progress"} tone="positive" /></div></section>

    <section className="assurance-summary"><div><div className="section-kicker">Control boundary</div><h2 className="mt-1 text-xl font-semibold text-white">The controller never sees evaluator labels.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#aaa7a1]">The controller reconciles from payment evidence, bounded investigation, and deterministic checks. Hidden truth is used only after the close to measure the result.</p><div className="assurance-flow mt-4"><span>Controller decision</span><span>Evidence</span><span>Verification</span><span>Truth evaluation</span></div></div><div className="lg:text-right"><ShieldCheck className="ml-auto h-8 w-8 text-[#c7ff54]" aria-hidden /><div className="mt-2 text-sm font-semibold text-white">Financial controls remain deterministic.</div><div className="mt-1 text-sm text-[#77746e]">AI investigates only.</div></div></section>

    <section className="border-b border-white/10 pb-6"><div className="section-kicker">Adversarial retest</div><div className="mt-2 grid gap-5 lg:grid-cols-[minmax(0,1fr)_auto]"><div><h2 className="text-xl font-semibold text-white">{fingerprint ? titleCase(fingerprint.pattern) : "Assurance report pending"}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#aaa7a1]">{fingerprint ? fingerprint.root_cause : "Run an audit to derive a measured failure fingerprint and targeted retest."}</p>{fingerprint ? <div className="mt-4 flex flex-wrap gap-2 text-xs text-[#aaa7a1]"><span>{compact(fingerprint.frequency)} observed</span><span>·</span><span>{money(fingerprint.exposure)} exposure</span><span>·</span><span>{fingerprint.target_anomalies.map(titleCase).join(", ")}</span></div> : null}</div><div className="flex flex-wrap items-start gap-2"><button type="button" className="button-primary" disabled={isBusy || !assurance} onClick={() => void runRedTeam(200)}><FlaskConical className="h-4 w-4" />Run targeted retest</button></div></div>{retest ? <div className={`mt-5 border-l-2 pl-4 text-sm ${retest.verdict === "SURVIVED" ? "border-[#70f0bf] text-[#70f0bf]" : "border-[#ff6b4a] text-[#ffb08d]"}`}>{titleCase(retest.verdict)} · retest score {retest.retest_score.toFixed(1)} · {compact(retest.retest_failures)} retest failures against {compact(retest.baseline_failures)} at baseline.</div> : null}</section>

    <details className="border-b border-white/10 pb-4"><summary className="cursor-pointer text-sm font-semibold text-[#c7c4bf]">Advanced evaluation</summary><div className="mt-5 grid gap-6 lg:grid-cols-2"><div><div className="section-kicker">Comparison</div><p className="mt-2 text-sm leading-6 text-[#aaa7a1]">Compare deterministic-only and AI-assisted runs on the same controlled world.</p><button type="button" className="button-secondary mt-4" disabled={isBusy} onClick={() => void runComparison()}>Run comparison <ArrowRight className="h-4 w-4" /></button>{comparison ? <div className="mt-4 divide-y divide-white/10 border-y border-white/10">{comparison.comparison.map((row) => <div key={row.mode} className="flex items-center justify-between gap-4 py-3 text-sm"><span className="text-[#aaa7a1]">{row.mode === "ai_assisted" ? "AI-assisted" : "Deterministic"}</span><span className="font-semibold text-white">{pct(row.metrics.accuracy, 2)} accuracy · {pct(row.metrics.f1, 2)} F1</span></div>)}</div> : null}</div><div><div className="section-kicker">Failure taxonomy</div><div className="mt-3 divide-y divide-white/10 border-y border-white/10">{Object.entries(metrics.failure_taxonomy).length ? Object.entries(metrics.failure_taxonomy).map(([name, count]) => <div key={name} className="flex items-center justify-between gap-4 py-3 text-sm"><span className="text-[#aaa7a1]">{titleCase(name)}</span><span className="font-semibold text-white">{compact(count)}</span></div>) : <div className="py-3 text-sm text-[#77746e]">No failure categories recorded.</div>}</div></div></div></details>
  </div>;
}

function Kpi({ label, value, detail, tone }: { label: string; value: string; detail: string; tone?: "positive" | "warning" | "danger" }) { return <div className="kpi-item"><div className="kpi-label">{label}</div><div className={`kpi-value ${tone ?? ""}`}>{value}</div><div className="kpi-detail">{detail}</div></div>; }
function recommendationAccent(recommendation: string) { if (recommendation === "CONTROLLED_DEPLOYMENT") return "emerald" as const; if (recommendation === "HUMAN_SUPERVISED") return "amber" as const; return "rose" as const; }
function Empty({ onClick }: { onClick: () => void }) { return <section className="border-y border-white/10 py-14 text-center"><h1 className="text-2xl font-semibold text-white">Assurance needs a completed audit</h1><p className="mt-2 text-sm text-[#9a9792]">Run the controller first, then Auditra can measure its decisions against hidden truth.</p><button type="button" className="button-secondary mt-5" onClick={onClick}>Open audit <ArrowRight className="h-4 w-4" /></button></section>; }